# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'

# Define services
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2
    ports:
      - 6379:6379
    networks:
      - app-network
  # App backend service
  backend:
    container_name: backend
    # Configuration for building the docker image for the backend service
    build:
      context: wildfire-watch-bc-api # Use an image built from the specified dockerfile in the `wildfirewatch-bc-api` directory.
      dockerfile: Dockerfile

    ports:
      - "8090:8090" # Forward the exposed port 8090 on the container to port 8090 on the host machine
    restart: on-failure

    working_dir: /app
    command: java -jar ca.bc.gov.wildfirewatch-0.0.1-SNAPSHOT.jar
    depends_on:
      - redis # This service depends on redis. Start that first.
    environment:
      # Pass environment variables to the service
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-network
  frontend:
    container_name: frontend
    build:
      context: wildfire-watch-bc-ui # Use an image built from the specified dockerfile in the `wildfire-watch-bc-api` directory.
      dockerfile: Dockerfile
    ports:
      - "80:80" # Forward the exposed port 80 on the container to port 80 on the host machine
    restart: always
    depends_on:
      - backend # This service depends on mysql. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - frontend
networks:
  app-network:
    driver: bridge
  frontend:
